version: "3.9"
services:
  mongodb:
     image: mongo
     restart: always
     ports:
       - "27017:27017"
     networks:
      - mongo-compose-network
 
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge